before_script:
  - . $NVM_DIR/nvm.sh
  - nvm --version
  - nvm ls
  - nvm install $NODE_VERSION --latest-npm
  - nvm use $NODE_VERSION
  - npm -version

stages:
  - build
  - sonar

build-unit-simple:
  stage: build
  script:
    - cd unit-simple
    - npm ci
    - npm run build
  artifacts:
    paths:
      - unit-simple/dist/
    expire_in: 2 days

sonar:
  stage: sonar
  script:
    - $SONAR_SCANNER_HOME/bin/sonar-scanner -Dsonar.login=$SONAR_LOGIN
  artifacts:
    expire_in: 2 days

