env:
  browser: true
  es2021: true
extends: standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ["tsconfig.json"]
rules: {
  'padded-blocks': ['error', { blocks: 'never', classes: 'always', switches: 'never' }],
  'max-len': ['error', { 'code': 120 }],
  'no-unused-vars': ['off'],
  'no-undef': ['off']
}
